---
server:
    install: '1'
    packages: [vim, git, htop, npm, imagemagick]
    timezone: Europe/London
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: tinkr, ip: 192.168.33.88, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: tinkr_root.vb
hhvm:
    install: '1'
mariadb:
    install: '1'
    root_password: root
    database: db
    user: user
    password: password
    dump: ''
redis:
    install: '1'
    port: '6379'
elasticsearch:
    install: '1'
    port: '9200'
    version: 1.5.2
drupal:
    docroot: /vagrant/www/drupal
    servername: tinkr.vb
    confname: drupal
php:
  install: '1'
  ppa: php5-5.6
  packages: [php5-cli, php5-intl, php5-mcrypt, php5-common, php5-mysql, php5-gd]
